export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const GET_CART = "GET_CART";

export const ADD_TO_CART = "ADD_TO_CART";

export const ADD_AND_DELETE_IN_FAVS = 'ADD_AND_DELETE_IN_FAVS';

export const GET_ITEM = 'GET_ITEM';
